apiVersion: v1
kind: Service
metadata:
  name: udagram-reverseproxy
  labels:
    run: udagram-reverseproxy
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    run: udagram-reverseproxy
  type: LoadBalancer