apiVersion: v1
kind: ConfigMap
data:
  # Configuration values can be set as key-value properties
  POSTGRES_HOST: tomdatabase.cvqp9a8iqbnm.us-east-1.rds.amazonaws.com
  POSTGRES_DB: postgres
  AWS_BUCKET: arn:aws:s3:::test-472916243171-dev
  AWS_REGION: us-east-1
  URL: http://10.100.93.209:8100
metadata:
  name: env-config